version: '3.8'
services:

  php-fpm:
    container_name: php-fpm
    working_dir: /app
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

  # db:
  #   container_name: db
  #   image: mysql
  #   tty: true
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #     MYSQL_DATABASE: db
  #     MYSQL_PASSWORD: pass
  #   ports:                                                                                                              
  #     - 3306:3306
  #   volumes:
  #     - dbdata:/var/lib/mysql

  db:
    container_name: db
    image: postgres
    tty: true
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
       - dbdata:/var/lib/postgresql/data

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm

networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local
  